backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "index"
    label: "Manifestas (index.json)"
    files:
      - label: "Index JSON"
        name: "index"
        file: "catalog/index.json"
        fields:
          - { label: "version", name: "version", widget: "number" }
          - { label: "updatedAt", name: "updatedAt", widget: "datetime" }
          - label: "files"
            name: "files"
            widget: "object"
            fields:
              - { label: "videos", name: "videos", widget: "string" }
              - { label: "categories", name: "categories", widget: "string" }
              # categoryItems NEBENAUDOJAM – išimta iš manifest
              # - { label: "categoryItems", name: "categoryItems", widget: "string" }

  - name: "videos"
    label: "Įrašai (videos.json)"
    files:
      - label: "Visi įrašai"
        name: "videos"
        file: "catalog/videos.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "id", name: "id", widget: "string" }
              - { label: "type", name: "type", widget: "select", options: ["youtube_video","youtube_playlist","mp4"] }
              - { label: "url", name: "url", widget: "string" }
              - { label: "title (optional)", name: "title", widget: "string", required: false, hint: "Palik tuščią – programėlė paims pavadinimą iš YouTube" }
              - { label: "thumbnail (optional)", name: "thumbnail", widget: "string", required: false }
              - label: "categories"
                name: "categories"
                widget: "relation"
                collection: "categories"
                search_fields: ["items.*.title", "items.*.id"]
                value_field: "items.*.id"
                display_fields: ["items.*.title"]
                multiple: true
                required: false
                hint: "Pasirink kelias kategorijas (nebūtina)"
              - { label: "tags (optional)", name: "tags", widget: "list", required: false }
              - { label: "lang (optional)", name: "lang", widget: "string", required: false }

  - name: "categories"
    label: "Kategorijos (categories.json)"
    files:
      - label: "Kategorijos"
        name: "categories"
        file: "catalog/categories.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "id", name: "id", widget: "string" }
              - { label: "title", name: "title", widget: "string" }

  # categoryItems kolekcijos NĖRA – nuo šiol priskyrimas vyksta tiesiog videos.items[].categories