backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "index"
    label: "Manifestas (index.json)"
    files:
      - label: "Index JSON"
        name: "index"
        file: "catalog/index.json"
        fields:
          - { label: "version", name: "version", widget: "number" }
          - { label: "updatedAt", name: "updatedAt", widget: "datetime" }
          - label: "files"
            name: "files"
            widget: "object"
            fields:
              - { label: "videos", name: "videos", widget: "string" }

  - name: "videos"
    label: "Įrašai (videos.json)"
    files:
      - label: "Visi įrašai"
        name: "videos"
        file: "catalog/videos.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "id", name: "id", widget: "string" }
              - { label: "type", name: "type", widget: "select",
                  options: [ "youtube_video","youtube_playlist","youtube_channel_playlists","youtube_channel_shorts","mp4" ] }
              - { label: "url", name: "url", widget: "string" }

              # >>> NAUJAS LAUKAS – ranka įvedamas UC... channelId
              - { label: "channelId (optional, UC…)", name: "channelId", widget: "string", required: false, hint: "Pvz.: UC7RZRFCrN0p7U1a7F8Jc9cw. Naudojamas kanalų playlists/shorts puslapiams be brangių search.list" }

              - { label: "title (optional)", name: "title", widget: "string", required: false, hint: "Gali palikti tuščią – paimsim iš cache/YT (pigus call) kai reikia" }
              - { label: "thumbnail (optional)", name: "thumbnail", widget: "string", required: false }

              - label: "categories (optional)"
                name: "categories"
                widget: "list"
                required: false
                hint: "Pvz.: Mokslas, DIY (gali pridėti kelias kategorijas)"
                field:
                  label: "category"
                  name: "category"
                  widget: "string"

              - label: "tags (optional)"
                name: "tags"
                widget: "list"
                required: false
                field:
                  label: "tag"
                  name: "tag"
                  widget: "string"

              - { label: "lang (optional)", name: "lang", widget: "string", required: false }